apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    name: web
    app: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: web 
          image: pardeep889/todo:latest1
          env:
            - name: "DBHOST"
              value: "mongodb://todo-mongodb-replicaset-0.todo-mongodb-replicaset,todo-mongodb-replicaset-1.todo-mongodb-replicaset,todo-mongodb-replicaset-2.todo-mongodb-replicaset:27017"
          ports:
          - containerPort: 3000